version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    commit-message:
      prefix: "CI"
    labels:
      - "ci"
    groups:
      github-actions:
        patterns:
          - "*"
