#pragma once

#ifndef FASTFETCH_INCLUDED_TEXT_MODIFIER
#define FASTFETCH_INCLUDED_TEXT_MODIFIER

#define FASTFETCH_TEXT_MODIFIER_BOLT  "\033[1m"
#define FASTFETCH_TEXT_MODIFIER_ERROR "\033[1;31m"
#define FASTFETCH_TEXT_MODIFIER_RESET "\033[m"

#endif
