#pragma once

// For "fastfetch.c" and "flashfetch.c"

#include "modules/os/os.h"
#include "modules/battery/battery.h"
#include "modules/bios/bios.h"
#include "modules/bluetooth/bluetooth.h"
#include "modules/brightness/brightness.h"
#include "modules/board/board.h"
#include "modules/break/break.h"
#include "modules/cpu/cpu.h"
#include "modules/cpuusage/cpuusage.h"
#include "modules/command/command.h"
#include "modules/colors/colors.h"
#include "modules/cursor/cursor.h"
#include "modules/custom/custom.h"
#include "modules/datetime/datetime.h"
#include "modules/disk/disk.h"
#include "modules/display/display.h"
#include "modules/font/font.h"
#include "modules/gamepad/gamepad.h"
#include "modules/gpu/gpu.h"
#include "modules/host/host.h"
#include "modules/kernel/kernel.h"
#include "modules/locale/locale.h"
#include "modules/separator/separator.h"
#include "modules/title/title.h"
#include "modules/jsonconfig/jsonconfig.h"
