#pragma once

// For "fastfetch.h"

#include "modules/battery/option.h"
#include "modules/bios/option.h"
#include "modules/bluetooth/option.h"
#include "modules/board/option.h"
#include "modules/brightness/option.h"
#include "modules/cpu/option.h"
#include "modules/cpuusage/option.h"
#include "modules/cursor/option.h"
#include "modules/custom/option.h"
#include "modules/command/option.h"
#include "modules/datetime/option.h"
#include "modules/disk/option.h"
#include "modules/display/option.h"
#include "modules/host/option.h"
#include "modules/gpu/option.h"
#include "modules/kernel/option.h"
#include "modules/os/option.h"
#include "modules/separator/option.h"
#include "modules/title/option.h"
