name: General Bug Report
description: If something is not working as expected (wrong output, missing info, etc)
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! We will try hard to solve the issue.
        However since platforms and hardwares vary greatly, it can be hard to find the root cause of an issue.
        Providing the following information may help us greatly. Thanks in advance!
  - type: checkboxes
    attributes:
      label: Read the FAQ first
      description: Please check if the issue is already covered in the FAQ.
      options:
        - label: I have checked the FAQ but the issue is not covered
          required: true
  - type: markdown
    attributes:
      value: "### General description of the bug"
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: I was trying to [...] but [...]
    validations:
      required: true
  - type: input
    attributes:
      label: Version used
      description: Fastfetch version used. Please use the latest version (found in the [releases](https://github.com/fastfetch-cli/fastfetch/releases)) if possible.
      placeholder: Result of `fastfetch --version`
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Bug prevalence
      description: How often does the bug occur?
      options:
        -
        - Always
        - Sometimes
        - Rarely
        - Once
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Regression
      description: Did it work in an older version?
      options:
        -
        - Not sure
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation
      description: Where did you install fastfetch from?
      options:
        -
        - GitHub Releases
        - GitHub Actions (nightly)
        - Built from source
        - Package manager
    validations:
      required: true
  - type: input
    attributes:
      label: Package manager
      description: Which package manager did you use if applicable?
      placeholder: e.g. `apt`, `pacman`, `brew`, `scoop`
  - type: markdown
    attributes:
      value: '### Often helpful information'
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    attributes:
      label: Configuration
      description: If applicable, paste your configuration file here.
      placeholder: cat ~/.config/fastfetch/config.jsonc
      render: jsonc
  - type: textarea
    attributes:
      label: System information
      description: Output of `fastfetch -c all.jsonc --stat --format json`
      placeholder: |
        Note that this output will contain you public IP.
        If it is not relevant for the issue, feel free to remove it before uploading.
      render: jsonc
    validations:
      required: true
  - type: textarea
    attributes:
      label: Features built-in
      description: Output of `fastfetch --list-features`
      render: text
    validations:
      required: true
