.TH man 1 "Nov 11 2024" "VERSION 2.29.0" "Fastfetch man page"
.SH NAME
fastfetch - a neofetch-like tool for fetching system information and displaying them in a pretty way
.SH SYNOPSIS
.B fastfetch
[\fIOPTIONS\fR]
.SH DESCRIPTION
A maintained, feature-rich and performance oriented, neofetch like system information tool.
.SH WIKI
Fastfetch wiki : https://github.com/fastfetch-cli/fastfetch/wiki/Configuration
.SH CONFIGURATION
.SS Fetch Structure 
The structure of a fetch describes the modules that should be included in the output. It consists of a string of modules, separated by a colon (:).  To list all available modules, use --list-modules 

.SS Config Files 
Fastfetch uses JSONC based format for configuration. Fastfetch doesn't generate config file automatically; it should be generated manually by \fB--gen-config.\fR The config file will be saved in \fB~/.config/fastfetch/config.jsonc\fR by default. 

A JSONC config file is a JSON file that also supports comments with (// and /* */).  Those files must have the extension '.jsonc'. 

The specified configuration/preset files are searched in the following order: 

\fB1.\fR relative to the current working directory 

\fB2.\fR relative to ~/.local/share/fastfetch/presets/ 

\fB3.\fR relative to /usr/share/fastfetch/presets/ 

Fastfetch provides some default presets. List them with --list-presets. 
.SH OPTIONS
Parsing is not case sensitive. E.g. \fB--lib-PCI\fR is equal to \fB--Lib-Pci\fR.     

If a value is between square brakets, it is optional. An optional boolean value defaults to true if not specified.     

More detailed help messages for each options can be printed with \fB-h <option_without_dash_prefix>\fR.     

All options can be made permanent with command \fBfastfetch <options> --gen-config\fR. 

.SS Informative:
.TP
\fB\-h, \-\-help\fR [\fI?command\fR]
 Show this message, or help for a specific command 

.TP
\fB\-v, \-\-version\fR 
 Show the full version of fastfetch 

.TP
\fB\-\-version-raw\fR 
 Show the raw version string (major.minor.patch) 

.TP
\fB\-\-list-config-paths\fR 
 List search paths of config files 

.TP
\fB\-\-list-data-paths\fR 
 List search paths of presets and logos 

.TP
\fB\-\-list-logos\fR 
 List available logos 

.TP
\fB\-\-list-modules\fR 
 List available modules 

.TP
\fB\-\-list-presets\fR 
 List presets fastfetch knows about 

.TP
\fB\-\-list-features\fR 
 List the supported features fastfetch was compiled with 

.TP
\fB\-\-print-logos\fR 
 Print available logos 

.TP
\fB\-\-print-structure\fR 
 Print the default structure 

.TP
\fB\-\-format\fR \fIenum\fR
 Set output format 

.SS Config:
.TP
\fB\-c, \-\-config\fR \fIconfig\fR
 Specify the config file or preset to be loaded 

.TP
\fB\-\-gen-config\fR [\fI?path\fR]
 Generate a config file to specified path with options specified in the command line (if any) 

.TP
\fB\-\-gen-config-force\fR [\fI?path\fR]
 Generate a config file to specified path. Overwrite the existing one 

.SS General:
.TP
\fB\-\-thread\fR [\fI?bool\fR]
 Use separate threads to send HTTP requests 

.TP
\fB\-\-escape-bedrock\fR [\fI?bool\fR]
 On Bedrock Linux, whether to escape the bedrock jail 

.TP
\fB\-\-wmi-timeout\fR \fInum\fR
 Set the timeout (ms) for WMI queries 

.TP
\fB\-\-processing-timeout\fR \fInum\fR
 Set the timeout (ms) when waiting for child processes 

.TP
\fB\-\-ds-force-drm\fR [\fI?enum\fR]
 Set if only DRM should be used to detect displays 

.TP
\fB\-\-detect-version\fR [\fI?bool\fR]
 Whether to detect and display the version of terminal, shell and editor 

.SS Logo:
.TP
\fB\-l, \-\-logo\fR \fIlogo\fR
 Set the logo source. Use "none" to disable the logo 

.TP
\fB\-\-logo-type\fR \fIenum\fR
 Set the type of the logo given in "--logo" 

.TP
\fB\-\-logo-width\fR \fInum\fR
 Set the width of the logo (in characters), if it is an image 

.TP
\fB\-\-logo-height\fR \fInum\fR
 Set the height of the logo (in characters), if it is an image 

.TP
\fB\-\-logo-preserve-aspect-ratio\fR [\fI?bool\fR]
 Set if the logo should fill the specified width and height as much as possible without stretching 

.TP
\fB\-\-logo-color-[1-9]\fR \fIcolor\fR
 Overwrite a color in the logo 

.TP
\fB\-\-logo-padding\fR \fInum\fR
 Set the padding on the left and the right of the logo 

.TP
\fB\-\-logo-padding-left\fR \fInum\fR
 Set the padding on the left of the logo 

.TP
\fB\-\-logo-padding-right\fR \fInum\fR
 Set the padding on the right of the logo 

.TP
\fB\-\-logo-padding-top\fR \fInum\fR
 Set the padding on the top of the logo 

.TP
\fB\-\-logo-print-remaining\fR [\fI?bool\fR]
 Whether to print the remaining logo, if it has more lines than modules to display 

.TP
\fB\-\-logo-position\fR \fIenum\fR
 Set the position of the logo should be displayed 

.TP
\fB\-\-logo-recache\fR [\fI?bool\fR]
 If true, regenerate image logo cache 

.TP
\fB\-\-file\fR \fIpath\fR
 Short for --logo-type file --logo <path> 

.TP
\fB\-\-file-raw\fR \fIpath\fR
 Short for --logo-type file-raw --logo <path> 

.TP
\fB\-\-data\fR \fIdata\fR
 Short for --logo-type data --logo <data> 

.TP
\fB\-\-data-raw\fR \fIdata\fR
 Short for --logo-type data-raw --logo <data> 

.TP
\fB\-\-raw\fR \fIpath\fR
 Short for --logo-type raw --logo <path> 

.TP
\fB\-\-sixel\fR \fIpath\fR
 Short for --logo-type sixel --logo <path> 

.TP
\fB\-\-kitty\fR \fIpath\fR
 Short for --logo-type kitty --logo <path> 

.TP
\fB\-\-kitty-direct\fR \fIpath\fR
 Short for --logo-type kitty-direct --logo <path> 

.TP
\fB\-\-iterm\fR \fIpath\fR
 Short for --logo-type iterm --logo <path> 

.TP
\fB\-\-chafa\fR \fIpath\fR
 Short for --logo-type chafa --logo <path> 

.TP
\fB\-\-chafa-fg-only\fR [\fI?bool\fR]
 Produce character-cell output using foreground colors only 

.TP
\fB\-\-chafa-symbols\fR \fIstr\fR
 Specify character symbols to employ in final output 

.TP
\fB\-\-chafa-canvas-mode\fR \fIenum\fR
 Determine how colors are used in the output 

.TP
\fB\-\-chafa-color-space\fR \fIenum\fR
 Set color space used for quantization 

.TP
\fB\-\-chafa-dither-mode\fR \fIenum\fR
 Set output dither mode (No effect with 24-bit color) 

.SS Display:
.TP
\fB\-s, \-\-structure\fR \fIstructure\fR
 Set the structure of the fetch 

.TP
\fB\-\-stat\fR [\fI?bool\fR]
 Show time usage (in ms) for individual modules 

.TP
\fB\-\-pipe\fR [\fI?bool\fR]
 Disable colors 

.TP
\fB\-\-color-keys\fR \fIcolor\fR
 Set the color of the keys 

.TP
\fB\-\-color-title\fR \fIcolor\fR
 Set the color of the title 

.TP
\fB\-\-color-output\fR \fIcolor\fR
 Set the color of module output 

.TP
\fB\-\-color-separator\fR \fIcolor\fR
 Set the color of the key-value separator 

.TP
\fB\-\-color\fR \fIcolor\fR
 Set the color of both the keys and title 

.TP
\fB\-\-key-width\fR \fInum\fR
 Align the width of keys to <num> characters 

.TP
\fB\-\-key-padding-left\fR \fInum\fR
 Set the left padding of keys to <num> characters 

.TP
\fB\-\-key-type\fR \fIenum\fR
 Set whether to show icon before string keys 

.TP
\fB\-\-bright-color\fR [\fI?bool\fR]
 Set if the keys, title and ASCII logo should be printed in bright color 

.TP
\fB\-\-separator\fR \fIstr\fR
 Set the separator between key and value 

.TP
\fB\-\-show-errors\fR [\fI?bool\fR]
 Print occurring errors 

.TP
\fB\-\-disable-linewrap\fR [\fI?bool\fR]
 Whether to disable line wrap during the run 

.TP
\fB\-\-hide-cursor\fR [\fI?bool\fR]
 Whether to hide the cursor during the run 

.TP
\fB\-\-percent-type\fR \fInum\fR
 Set the percentage output type 

.TP
\fB\-\-percent-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when formatting percentage numbers 

.TP
\fB\-\-percent-color-green\fR \fIcolor\fR
 Set color used in green state of percentage bars and numbers 

.TP
\fB\-\-percent-color-yellow\fR \fIcolor\fR
 Set color used in yellow state of percentage bars and numbers 

.TP
\fB\-\-percent-color-red\fR \fIcolor\fR
 Set color used in red state of percentage bars and numbers 

.TP
\fB\-\-bar-char-elapsed\fR \fIstr\fR
 Set the character to use in elapsed part of percentage bars 

.TP
\fB\-\-bar-char-total\fR \fIstr\fR
 Set the character to use in total part of percentage bars 

.TP
\fB\-\-bar-border-left\fR \fIstring\fR
 Set the string to use at left border of percentage bars 

.TP
\fB\-\-bar-border-right\fR \fIstring\fR
 Set the string to use at right border of percentage bars 

.TP
\fB\-\-bar-width\fR \fInum\fR
 Set the width of percentage bars, in number of characters 

.TP
\fB\-\-no-buffer\fR [\fI?bool\fR]
 Set if the stdout application buffer should be disabled 

.TP
\fB\-\-size-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when formatting sizes 

.TP
\fB\-\-size-binary-prefix\fR \fIenum\fR
 Set the binary prefix to used when formatting sizes 

.TP
\fB\-\-size-max-prefix\fR \fIenum\fR
 Set the largest binary prefix to use when formatting sizes 

.TP
\fB\-\-freq-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when printing CPU / GPU frequency in GHz 

.TP
\fB\-\-temp-unit\fR \fIenum\fR
 Set the unit of the temperature 

.TP
\fB\-\-temp-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when printing temperature 

.TP
\fB\-\-temp-color-green\fR \fIcolor\fR
 Set color used in green state of temperature values 

.TP
\fB\-\-temp-color-yellow\fR \fIcolor\fR
 Set color used in yellow state of temperature values 

.TP
\fB\-\-temp-color-red\fR \fIcolor\fR
 Set color used in red state of temperature values 

.SS Module specific:
.TP
\fB\-\-title-fqdn\fR [\fI?bool\fR]
 Set if the title should use fully qualified domain name 

.TP
\fB\-\-title-color-user\fR \fIcolor\fR
 Set color of the user name (left part) 

.TP
\fB\-\-title-color-at\fR \fIcolor\fR
 Set color of the @ symbol (middle part) 

.TP
\fB\-\-title-color-host\fR \fIcolor\fR
 Set color of the host name (right part) 

.TP
\fB\-\-separator-string\fR \fIstr\fR
 Set the string to be printed by the separator line 

.TP
\fB\-\-separator-output-color\fR \fIcolor\fR
 Set the color of the separator line 

.TP
\fB\-\-separator-length\fR \fInum\fR
 Set the length of the separator line 

.TP
\fB\-\-disk-folders\fR \fIpath\fR
 A colon (semicolon on Windows) separated list of folder paths to be detected 

.TP
\fB\-\-disk-show-regular\fR [\fI?bool\fR]
 Set if regular volume should be printed 

.TP
\fB\-\-disk-show-external\fR [\fI?bool\fR]
 Set if external volume should be printed 

.TP
\fB\-\-disk-show-hidden\fR [\fI?bool\fR]
 Set if hidden volumes should be printed 

.TP
\fB\-\-disk-show-subvolumes\fR [\fI?bool\fR]
 Set if subvolumes should be printed 

.TP
\fB\-\-disk-show-readonly\fR [\fI?bool\fR]
 Set if read only volumes should be printed 

.TP
\fB\-\-disk-show-unknown\fR [\fI?bool\fR]
 Set if unknown (unable to detect sizes) volumes should be printed 

.TP
\fB\-\-disk-use-available\fR [\fI?bool\fR]
 Use f_bavail (lpFreeBytesAvailableToCaller for Windows) instead of f_bfree to calculate used bytes 

.TP
\fB\-\-diskio-detect-total\fR \fIbool\fR
 Detect total bytes instead of current rate 

.TP
\fB\-\-diskio-name-prefix\fR \fIstr\fR
 Show disks with given name prefix only 

.TP
\fB\-\-diskio-wait-time\fR \fInum\fR
 Set the wait time (in ms) when detecting disk usage 

.TP
\fB\-\-physicaldisk-name-prefix\fR \fIstr\fR
 Show disks with given name prefix only 

.TP
\fB\-\-physicaldisk-temp\fR [\fI?bool\fR]
 Detect and display SSD temperature if supported 

.TP
\fB\-\-bluetooth-show-disconnected\fR [\fI?bool\fR]
 Set if disconnected bluetooth devices should be printed 

.TP
\fB\-\-packages-disabled\fR \fIstring\fR
 A colon separated list of package managers to be disabled when detecting 

.TP
\fB\-\-display-compact-type\fR \fIenum\fR
 Set if all displays should be printed in one line 

.TP
\fB\-\-display-precise-refresh-rate\fR [\fI?bool\fR]
 Set if decimal refresh rates should not be rounded into integers when printing 

.TP
\fB\-\-display-order\fR \fIenum\fR
 Set the order should be used when printing displays 

.TP
\fB\-\-brightness-ddcci-sleep\fR \fInum\fR
 Set the sleep times (in ms) when sending DDC/CI requests 

.TP
\fB\-\-brightness-compact\fR \fIbool\fR
 Set if multiple results should be printed in one line 

.TP
\fB\-\-sound-type\fR \fIenum\fR
 Set what type of sound devices should be printed 

.TP
\fB\-\-battery-use-setup-api\fR [\fI?bool\fR]
 Set if "SetupAPI" should be used on Windows to detect battery info 

.TP
\fB\-\-cpu-temp\fR [\fI?bool\fR]
 Detect and display CPU temperature if supported 

.TP
\fB\-\-cpu-show-pe-core-count\fR [\fI?bool\fR]
 Detect and display CPU frequency of different core types (eg. Pcore and Ecore) if supported 

.TP
\fB\-\-cpucache-compact\fR [\fI?bool\fR]
 Show all CPU caches in one line 

.TP
\fB\-\-cpuusage-separate\fR [\fI?bool\fR]
 Display CPU usage per CPU logical core, instead of an average result 

.TP
\fB\-\-cpuusage-wait-time\fR \fInum\fR
 Set the wait time (in ms) when detecting CPU usage 

.TP
\fB\-\-de-slow-version-detection\fR [\fI?bool\fR]
 Set if DE version should be detected with slow operations 

.TP
\fB\-\-gpu-temp\fR [\fI?bool\fR]
 Detect and display GPU temperature if supported 

.TP
\fB\-\-gpu-driver-specific\fR [\fI?bool\fR]
 Use driver specific method to detect more detailed GPU information (memory usage, core count, etc) 

.TP
\fB\-\-gpu-detection-method\fR \fIenum\fR
 Force using a specified method to detect GPUs 

.TP
\fB\-\-gpu-hide-type\fR \fIenum\fR
 Specify the type of GPUs should not be printed 

.TP
\fB\-\-battery-temp\fR [\fI?bool\fR]
 Detect and display Battery temperature if supported 

.TP
\fB\-\-loadavg-ndigits\fR \fInum\fR
 Set the number of digits to keep after the decimal point when printing load average 

.TP
\fB\-\-loadavg-compact\fR [\fI?bool\fR]
 Show load average values in one line 

.TP
\fB\-\-localip-show-ipv4\fR [\fI?bool\fR]
 Show IPv4 addresses in local ip module 

.TP
\fB\-\-localip-show-ipv6\fR [\fI?bool\fR]
 Show IPv6 addresses in local ip module 

.TP
\fB\-\-localip-show-mac\fR [\fI?bool\fR]
 Show mac addresses in local ip module 

.TP
\fB\-\-localip-show-loop\fR [\fI?bool\fR]
 Show loop back addresses (127.0.0.1) in local ip module 

.TP
\fB\-\-localip-show-mtu\fR [\fI?bool\fR]
 Show net interface's MTU (Maximum Transmission Unit) size in bytes 

.TP
\fB\-\-localip-show-speed\fR [\fI?bool\fR]
 Show net interface's link speed with human-readable format (or an 1Mb units integer in JSON format) 

.TP
\fB\-\-localip-show-prefix-len\fR [\fI?bool\fR]
 Show network prefix length (/N) in local ip module 

.TP
\fB\-\-localip-name-prefix\fR \fIstr\fR
 Show interfaces with given interface name prefix only 

.TP
\fB\-\-localip-default-route-only\fR [\fI?bool\fR]
 Show the interface that is used for default routing only 

.TP
\fB\-\-localip-show-all-ips\fR [\fI?bool\fR]
 Show all IPs bound to the same interface. By default only the first IP is shown 

.TP
\fB\-\-localip-show-flags\fR [\fI?bool\fR]
 Show net interface flags in local ip module 

.TP
\fB\-\-localip-compact\fR [\fI?bool\fR]
 Show all IPs in one line 

.TP
\fB\-\-dns-show-type\fR \fIenum\fR
 Specify the type of DNS servers should be detected 

.TP
\fB\-\-netio-name-prefix\fR \fIstr\fR
 Show interfaces with given name prefix only 

.TP
\fB\-\-netio-default-route-only\fR [\fI?bool\fR]
 Show the interfac that is used for default routing only 

.TP
\fB\-\-netio-detect-total\fR \fIbool\fR
 Detect total bytes instead of current rate 

.TP
\fB\-\-netio-wait-time\fR \fInum\fR
 Set the wait time (in ms) when detecting network usage 

.TP
\fB\-\-publicip-timeout\fR \fInum\fR
 Time in milliseconds to wait for the public ip server to respond 

.TP
\fB\-\-publicip-url\fR \fIstr\fR
 The URL of public IP detection server to be used 

.TP
\fB\-\-publicip-ipv6\fR \fIbool\fR
 Whether to use IPv6 for public IP detection server 

.TP
\fB\-\-weather-location\fR \fIstr\fR
 Set the location to be used 

.TP
\fB\-\-weather-timeout\fR \fInum\fR
 Time in milliseconds to wait for the weather server to respond 

.TP
\fB\-\-weather-output-format\fR \fIstr\fR
 The output weather format to be used 

.TP
\fB\-\-wm-detect-plugin\fR [\fI?bool\fR]
 Set if window manager plugin should be detected on supported platforms 

.TP
\fB\-\-users-compact\fR [\fI?bool\fR]
 Show all active users in one line 

.TP
\fB\-\-users-myself-only\fR [\fI?bool\fR]
 Show only current user 

.TP
\fB\-\-player-name\fR \fIstr\fR
 The name of the player to use for module Media and Player 

.TP
\fB\-\-opengl-library\fR \fIenum\fR
 Set the OpenGL context creation library to use 

.TP
\fB\-\-command-shell\fR \fIstr\fR
 Set the shell program to execute the command text 

.TP
\fB\-\-command-param\fR \fIstr\fR
 Set the parameter used when starting the shell 

.TP
\fB\-\-command-key\fR \fIstr\fR
 Set the module key to display 

.TP
\fB\-\-command-text\fR \fIstr\fR
 Set the command text to be executed 

.TP
\fB\-\-colors-symbol\fR \fIenum\fR
 Set the symbol to be printed by Colors module 

.TP
\fB\-\-colors-padding-left\fR \fInum\fR
 Set the number of white spaces to print before the symbol 

.TP
\fB\-\-colors-block-width\fR \fInum\fR
 Set the block width in spaces 

.TP
\fB\-\-colors-block-range-start\fR \fInum\fR
 Set the start range of colors in the blocks to print 

.TP
\fB\-\-colors-block-range-end\fR \fInum\fR
 Set the end range of colors in the blocks to print 

.SS General module:
.TP
\fB\-\-<module>-format\fR \fIformat\fR
 ['Set the format string to use for each specific module', 'To see how a format string works, use "fastfetch -h format".', 'To see help about a specific format string, use "fastfetch -h <module>-format"'] 

.TP
\fB\-\-<module>-key\fR \fIkey\fR
 ['Set the key to use for each specific module.', 'For modules which print multiple lines, the string is parsed', 'as a format string with the index as first character'] 

.TP
\fB\-\-<module>-key-color\fR \fIcolor\fR
 Override the global "--color-keys" option for each specific module 

.TP
\fB\-\-<module>-key-icon\fR \fIstring\fR
 Set the icon to be displayed by "--key-type icon" 

.TP
\fB\-\-<module>-output-color\fR \fIcolor\fR
 Override the global "--color-output" option for each specific module 

.TP
\fB\-\-<module>-key-width\fR \fInum\fR
 Override the global "--key-width" option for each specific module 

.TP
\fB\-\-<module>-percent-green\fR \fInum\fR
 ['Threshold of percentage colors', 'Value less then percent-green will be shown in green'] 

.TP
\fB\-\-<module>-percent-yellow\fR \fInum\fR
 ['Threshold of percentage colors', 'Value greater than percent-green and less then yellow will be shown in yellow', 'Value greater than percent-yellow will be shown in red'] 

.TP
\fB\-\-<module>-temp-green\fR \fInum\fR
 ['Threshold of temperature colors', 'Value less then temp-green will be shown in green'] 

.TP
\fB\-\-<module>-temp-yellow\fR \fInum\fR
 ['Threshold of temperature colors', 'Value greater than temp-green and less then yellow will be shown in yellow', 'Value greater than temp-yellow will be shown in red'] 

.SH EXAMPLES
.SS Config files:
.nf // ~/.config/fastfetch/config.jsonc 
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "modules": [ 
        "title", 
        "separator", 
        "module1", 
        { 
            "type": "module2", 
            "module2-option": "value" 
        } 
    ]
} 
.fi
.SH BUGS
Please report bugs to : https://github.com/fastfetch-cli/fastfetch/issues
