name: Reusable Haiku amd64

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cpa.sh {0}

    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: Start VM
        uses: cross-platform-actions/action@master
        with:
          operating_system: haiku
          version: 'r1beta5'
          shell: bash
          cpu_count: 4

      - name: Show system info
        run: uname -a

      - name: Install dependencies
        shell: cpa.sh {0} --reboot
        run: pkgman install -y git dbus_devel mesa_devel libelf_devel imagemagick_devel opencl_headers ocl_icd_devel vulkan_devel zlib_devel chafa_devel cmake llvm22_clang ninja pkgconfig python3.10 lua || pkgman install -y git dbus_devel mesa_devel libelf_devel imagemagick_devel opencl_headers ocl_icd_devel vulkan_devel zlib_devel chafa_devel cmake llvm22_clang ninja pkgconfig python3.10 lua

      - name: CMake configuration
        run: CC=clang CXX=clang++ cmake -GNinja -DSET_TWEAK=Off -DBUILD_TESTS=On -DENABLE_EMBEDDED_PCIIDS=On -DENABLE_EMBEDDED_AMDGPUIDS=On -DCMAKE_BUILD_TYPE=${{ vars.CMAKE_BUILD_TYPE || 'RelWithDebInfo' }} .

      - name: CMake build
        run: cmake --build . --target package --verbose -j4

      - name: List features
        run: ./fastfetch --list-features

      - name: Run normal
        run: time ./fastfetch -c presets/ci.jsonc --stat false

      - name: Run json
        run: time ./fastfetch -c presets/ci.jsonc --format json

      - name: Run flashfetch
        run: time ./flashfetch

      - name: Run tests
        run: ctest --output-on-failure

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: fastfetch-haiku-amd64
          path: ./fastfetch-*.*
