name: Reusable NetBSD amd64

on:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: ${{ vars.CMAKE_BUILD_TYPE || 'RelWithDebInfo' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: run VM
        uses: cross-platform-actions/action@13ec3be3fbdf
        with:
          operating_system: netbsd
          architecture: x86-64
          cpu_count: 4
          shell: bash
          version: '10.1'
          environment_variables: 'CMAKE_BUILD_TYPE'
          run: |
            uname -a
            sudo pkgin -y install clang cmake git pkgconf wayland vulkan-headers dconf dbus sqlite3 ImageMagick
            CC=clang cmake -DSET_TWEAK=Off -DBUILD_TESTS=On -DENABLE_EMBEDDED_PCIIDS=On -DENABLE_EMBEDDED_AMDGPUIDS=On .
            cmake --build . --target package --verbose -j4
            ./fastfetch --list-features
            time ./fastfetch -c presets/ci.jsonc --stat false
            time ./fastfetch -c presets/ci.jsonc --format json
            time ./flashfetch
            ldd fastfetch
            ctest --output-on-failure

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: fastfetch-netbsd-amd64
          path: ./fastfetch-*.*
