name: Reusable DragonFly amd64

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cpa.sh {0}

    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: Start VM
        uses: cross-platform-actions/action@master
        with:
          operating_system: dragonflybsd
          version: '6.4.2'
          shell: bash
          cpu_count: 4

      - name: Show system info
        run: |
          uname -a
          pkg --version

      - name: Update and install dependencies
        run: |
          sudo pkg update
          sudo pkg install -y llvm cmake git pkgconf binutils wayland vulkan-headers vulkan-loader libxcb libXrandr libX11 libdrm glib dconf dbus sqlite3-tcl egl opencl ocl-icd v4l_compat chafa libelf lua54 libva libvdpau

      - name: CMake configuration
        run: env CC=clang cmake -DSET_TWEAK=Off -DBUILD_TESTS=On -DENABLE_EMBEDDED_PCIIDS=On -DENABLE_EMBEDDED_AMDGPUIDS=On -DCMAKE_BUILD_TYPE=${{ vars.CMAKE_BUILD_TYPE || 'RelWithDebInfo' }} .

      - name: CMake build
        run: cmake --build . --target package --verbose -j4

      - name: List features
        run: ./fastfetch --list-features

      - name: Run normal
        run: time ./fastfetch -c presets/ci.jsonc --stat false

      - name: Run json
        run: time ./fastfetch -c presets/ci.jsonc --format json

      - name: Run flashfetch
        run: time ./flashfetch

      - name: Run ldd
        run: ldd fastfetch

      - name: Run tests
        run: ctest --output-on-failure

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: fastfetch-dragonfly-amd64
          path: ./fastfetch-*.*
