name: CI

on:
  - push
  - pull_request

jobs:
  spellcheck:
    uses: ./.github/workflows/build-spellcheck.yml

  no-features-test:
    name: No-features-test
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-no-features-test.yml
    secrets: inherit

  linux-hosts:
    name: Linux-${{ matrix.arch }}
    permissions:
      security-events: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: ubuntu-22.04
          - arch: aarch64
            runs-on: ubuntu-22.04-arm
    uses: ./.github/workflows/build-linux-hosts.yml
    with:
      arch: ${{ matrix.arch }}
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit

  linux-i686:
    name: Linux-i686
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-linux-i686.yml
    secrets: inherit

  linux-armv7l:
    name: Linux-armv7l
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-linux-armv7l.yml
    secrets: inherit

  linux-armv6l:
    name: Linux-armv6l
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-linux-armv6l.yml
    secrets: inherit

  linux-vms:
    name: Linux-${{ matrix.arch }}
    permissions:
      security-events: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: riscv64
          - arch: ppc64le
          - arch: s390x
    uses: ./.github/workflows/build-linux-vms.yml
    with:
      arch: ${{ matrix.arch }}
    secrets: inherit

  musl-amd64:
    name: Musl-amd64
    uses: ./.github/workflows/build-musl-amd64.yml
    secrets: inherit

  macos-hosts:
    name: macOS-${{ matrix.arch }}
    permissions:
      security-events: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: macos-15-intel
          - arch: aarch64
            runs-on: macos-latest
    uses: ./.github/workflows/build-macos-hosts.yml
    with:
      arch: ${{ matrix.arch }}
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit

  omnios-amd64:
    name: OmniOS-amd64
    uses: ./.github/workflows/build-omnios-amd64.yml
    secrets: inherit

  solaris-amd64:
    name: Solaris-amd64
    uses: ./.github/workflows/build-solaris-amd64.yml
    secrets: inherit

  freebsd-amd64:
    name: FreeBSD-amd64
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-freebsd-amd64.yml
    secrets: inherit

  openbsd-amd64:
    name: OpenBSD-amd64
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-openbsd-amd64.yml
    secrets: inherit

  netbsd-amd64:
    name: NetBSD-amd64
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-netbsd-amd64.yml
    secrets: inherit

  dragonfly-amd64:
    name: DragonFly-amd64
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-dragonfly-amd64.yml
    secrets: inherit

  haiku-amd64:
    name: Haiku-amd64
    permissions:
      security-events: write
      contents: read
    uses: ./.github/workflows/build-haiku-amd64.yml
    secrets: inherit

  windows-hosts:
    name: Windows-${{ matrix.arch }}
    permissions:
      security-events: write
      contents: read
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: windows-latest
            msystem: CLANG64
            msystem-lower: clang64
            msys-arch: x86_64
          - arch: aarch64
            runs-on: windows-11-arm
            msystem: CLANGARM64
            msystem-lower: clangarm64
            msys-arch: aarch64
    uses: ./.github/workflows/build-windows-hosts.yml
    with:
      arch: ${{ matrix.arch }}
      runs-on: ${{ matrix.runs-on }}
      msystem: ${{ matrix.msystem }}
      msystem-lower: ${{ matrix.msystem-lower }}
      msys-arch: ${{ matrix.msys-arch }}
    secrets: inherit

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'fastfetch-cli/fastfetch'
    name: Release
    needs:
      - linux-hosts
      - linux-i686
      - linux-armv7l
      - linux-armv6l
      - linux-vms
      - musl-amd64
      - macos-hosts
      - freebsd-amd64
      - openbsd-amd64
      - netbsd-amd64
      - dragonfly-amd64
      - solaris-amd64
      - omnios-amd64
      - haiku-amd64
      - windows-hosts
    permissions:
      contents: write
    uses: ./.github/workflows/build-release.yml
    with:
      ffversion: ${{ needs.linux-hosts.outputs.ffversion }}
    secrets: inherit
